### ISSUE TITLE
Option to leave if build fails

### ISSUE THREAD

**Issue by CySxL** [Co2333/Iridium#2]
![image](https://user-images.githubusercontent.com/15531137/148669252-282de8c5-fd18-49ab-acbc-b47d5fe86d1b.png)

**Comment by Lakr233** [comment]
It is simple since we have recipe to test against the exitCode, but could you tell me why that you have fail the process?

**Comment by Lakr233** [comment]
Done

![IMG_623A58C140F6-1](https://user-images.githubusercontent.com/25259084/148671356-eef8e815-8455-4a17-802b-fa063648678e.jpeg)

**Comment by CySxL** [comment]
> It is simple since we have recipe to test against the exitCode, but could you tell me why that you have fail the process?

Sure but I'm not really know why it failed tho. 

The app is Line in Appstore.(Link :https://apps.apple.com/tw/app/line/id443904275)

But the second time I tried it kinda "worked" as it has the decrypted ipa showed up but the logs were still showing error tho. So I'm not sure if the IPA of Line is valid or not.

Shall I send the fail logs to you here ?

**Comment by CySxL** [comment]
Just tried again. I think I got the same errors. ![image](https://user-images.githubusercontent.com/15531137/148678485-3dcb2026-0551-4bfb-a0d6-d9dcc76e3c3d.png)

**Comment by CySxL** [comment]
So it succeeded at the second try but there are still error logs inside : ![image](https://user-images.githubusercontent.com/15531137/148678601-dd60b2d1-10d8-4acc-925c-783c6db3cc36.jpeg)

**Comment by Lakr233** [comment]
I don’t have a test machine for iOS 13 over tfp0 interface. I’ll get back to you when I can.

**Comment by CySxL** [comment]
> I don’t have a test machine for iOS 13 over tfp0 interface. I’ll get back to you when I can. 

Sure please take your time !

And also I'm on iOS14.8, iPhone 11 Pro Max tho.
